"""Generate executable Triton for the validated TurboQuant schedule."""
from __future__ import annotations

from tsc.ir import Module


EXPECTED = ("load", "load", "load", "load", "decode", "rot", "cast", "rescale", "cast", "store")


def generate_triton(module: Module, *, indexing_delta: int = 0) -> str:
    """Emit a standalone fused kernel; reject IR this backend cannot preserve."""
    ops = tuple(ins.op for ins in module.instrs)
    if ops != EXPECTED:
        raise ValueError(f"unsupported IR order for Triton backend: {ops}")
    decode = module.instrs[4]
    bits = dict(decode.attrs)["bits"]
    out_type = module.outputs[0].type
    head_dim = out_type.shape[-1]
    if not isinstance(head_dim, int):
        raise ValueError("Triton backend needs a concrete head dimension")
    packed = module.inputs[0].type.shape[-1]
    if not isinstance(packed, int):
        raise ValueError("Triton backend needs a concrete packed dimension")
    return f'''# generated by Winnow tsc from optimized IR; do not edit
import torch
import triton
import triton.language as tl

@triton.jit
def generated_tq_dequant_kernel(packed, norms, centroids, pi, out, n_rows: tl.constexpr,
                                D: tl.constexpr, NB: tl.constexpr, BW: tl.constexpr,
                                BLOCK: tl.constexpr):
    rows = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    cols = tl.arange(0, D)
    mask = rows[:, None] < n_rows
    bit = cols[None, :] * BW
    byte = bit // 8
    shift = bit % 8
    base = packed + rows[:, None].to(tl.int64) * NB
    b0 = tl.load(base + byte + {indexing_delta}, mask=mask, other=0).to(tl.int32)
    b1 = tl.load(base + byte + 1 + {indexing_delta}, mask=mask & ((byte + 1) < NB), other=0).to(tl.int32)
    idx = ((b0 >> shift) | (b1 << (8 - shift))) & ((1 << BW) - 1)
    y = tl.load(centroids + idx)
    matrix = tl.load(pi + cols[:, None] * D + cols[None, :])
    x = tl.dot(y, matrix, allow_tf32=False)
    scale = tl.load(norms + rows, mask=rows < n_rows, other=0).to(tl.float32)
    tl.store(out + rows[:, None].to(tl.int64) * D + cols[None, :],
             (x * scale[:, None]).to(out.dtype.element_ty), mask=mask)

def run(packed, norms, centroids, pi):
    n_rows = packed.numel() // packed.shape[-1]
    out = torch.empty((n_rows, {head_dim}), device=packed.device, dtype=torch.bfloat16)
    generated_tq_dequant_kernel[(triton.cdiv(n_rows, 32),)](
        packed, norms, centroids, pi, out, n_rows,
        D={head_dim}, NB={packed}, BW={bits}, BLOCK=32, num_warps=4)
    return out.reshape(*packed.shape[:-1], {head_dim})
'''
