"""IR-driven Triton code generation.

The backend walks the instruction list and emits one code block per IR op, so
it accepts any valid IR: optimized (decode, store-folded cast) or unoptimized
(separate unpack, gather, and no-op casts), and any legal statement order.
There is no template matching against an expected op sequence.

Iteration space. Programs over a symbolic leading dim N are compiled to one
kernel program per BLOCK_N rows. The cache hands the kernel a
(B, H, MAXLEN, NB) buffer sliced to the first L positions, which is not
contiguous, so the prologue computes `src_row = (row // L) * MAXLEN + row % L`
exactly as the handwritten kernel does; for contiguous tensors MAXLEN == L
and the expression collapses.

Value realization. An input's resolved shape decides how its `load` is
realized: a tensor with a symbolic leading dim is streamed per row (packed
codes, norms), while a fully-concrete tensor is a resident table (codebook,
rotation matrix). Streamed loads bind a pointer and materialize lazily at the
consuming op, so `decode` can read two straddling bytes per index instead of
first materializing the packed row.

`indexing_delta` shifts every generated byte offset in the bit-extraction
block. It exists only for the negative control in the GPU differential
harness: a nonzero delta is an injected off-by-one that the numerical tests
must catch. It is not a feature flag and nothing in the runtime sets it.
"""
from __future__ import annotations

from tsc.errors import TSCError
from tsc.ir import Module

_TL_DTYPE = {"u8": "tl.uint8", "f16": "tl.float16", "bf16": "tl.bfloat16",
             "f32": "tl.float32"}
_TORCH_DTYPE = {"u8": "torch.uint8", "f16": "torch.float16",
                "bf16": "torch.bfloat16", "f32": "torch.float32"}


class _Val:
    """How an IR value exists in the generated kernel."""

    def __init__(self, kind: str, expr: str, dtype: str, meta: dict | None = None):
        self.kind = kind          # "reg" | "rows2d" | "rowvec" | "table"
        self.expr = expr          # register expression or pointer name
        self.dtype = dtype
        self.meta = meta or {}


class _Emitter:
    def __init__(self, module: Module, indexing_delta: int):
        self.module = module
        self.delta = indexing_delta
        self.lines: list[str] = []
        self.env: dict[str, _Val] = {}
        self.counter = 0

    def emit(self, line: str = "") -> None:
        self.lines.append(("    " + line) if line else "")

    def tmp(self, base: str) -> str:
        self.counter += 1
        return f"{base}_{self.counter}"

    # -- realization ---------------------------------------------------------
    def materialize(self, name: str) -> _Val:
        """Return `name` as a register value, emitting a load if needed."""
        val = self.env[name]
        if val.kind == "reg":
            return val
        var = self.tmp(name)
        if val.kind == "rows2d":
            nb = val.meta["nb"]
            if nb & (nb - 1):
                raise TSCError(
                    f"cannot materialize %{name} directly: row width {nb} is "
                    f"not a power of two (consume it through unpack/decode)")
            self._needs_offs_b(nb)
            self.emit(f"# materialize %{name}: per-row bytes")
            self.emit(f"{var} = tl.load({val.expr} + src_row[:, None].to(tl.int64)"
                      f" * {nb} + offs_b_{nb}, mask=rmask[:, None], other=0)")
            reg = _Val("reg", var, val.dtype)
        elif val.kind == "rowvec":
            self.emit(f"# materialize %{name}: one value per row")
            self.emit(f"{var} = tl.load({val.expr} + src_row, mask=rmask, other=0)")
            reg = _Val("reg", var, val.dtype)
        elif val.kind == "table":
            shape = val.meta["shape"]
            if len(shape) != 2:
                raise TSCError(
                    f"cannot materialize table %{name} of shape {shape} "
                    f"outside gather/decode")
            rows, cols = shape
            self.emit(f"# materialize %{name}: resident {rows}x{cols} table")
            self.emit(f"{var} = tl.load({val.expr} "
                      f"+ tl.arange(0, {rows})[:, None] * {cols} "
                      f"+ tl.arange(0, {cols})[None, :])")
            reg = _Val("reg", var, val.dtype)
        else:                                        # pragma: no cover
            raise TSCError(f"unknown value kind {val.kind}")
        self.env[name] = reg
        return reg

    def _needs_offs_b(self, nb: int) -> None:
        marker = f"offs_b_{nb}"
        if marker not in self.prologue_extras:
            self.prologue_extras[marker] = f"{marker} = tl.arange(0, {nb})[None, :]"

    # -- per-op emission -------------------------------------------------------
    def op_load(self, ins) -> None:
        src = ins.args[0]
        t = ins.result.type
        target = ins.result.name
        symbolic_lead = t.shape and isinstance(t.shape[0], str)
        if symbolic_lead and len(t.shape) == 2:
            self.env[target] = _Val("rows2d", f"{src}_ptr", t.dtype,
                                    {"nb": t.shape[1]})
        elif symbolic_lead and len(t.shape) == 1:
            self.env[target] = _Val("rowvec", f"{src}_ptr", t.dtype)
        elif not symbolic_lead:
            self.env[target] = _Val("table", f"{src}_ptr", t.dtype,
                                    {"shape": t.shape})
        else:
            raise TSCError(f"load of unsupported shape {t}")

    def _emit_extract(self, ptr: str, nb: int, bits: int, out_var: str) -> None:
        """Bit extraction, LSB-first, indices may straddle a byte boundary."""
        d = self.delta
        plus = f" + {d}" if d else ""
        if bits == 8:
            # A byte per index: the packed bytes are the indices.
            self.emit(f"{out_var} = tl.load({ptr} + src_row[:, None].to(tl.int64) * {nb}"
                      f" + offs_d[None, :]{plus}, mask=rmask[:, None], other=0).to(tl.int32)")
            return
        self.emit(f"bit_off = offs_d[None, :] * {bits}")
        self.emit("byte0 = bit_off // 8")
        self.emit("sh = bit_off % 8")
        self.emit(f"base = {ptr} + src_row[:, None].to(tl.int64) * {nb}")
        self.emit(f"b0 = tl.load(base + byte0{plus}, mask=rmask[:, None], other=0).to(tl.int32)")
        self.emit(f"hi_ok = rmask[:, None] & ((byte0 + 1) < {nb})")
        self.emit(f"b1 = tl.load(base + byte0 + 1{plus}, mask=hi_ok, other=0).to(tl.int32)")
        self.emit(f"{out_var} = ((b0 >> sh) | (b1 << (8 - sh))) & {(1 << bits) - 1}")

    def op_unpack(self, ins) -> None:
        src = self.env[ins.args[0]]
        bits = dict(ins.attrs)["bits"]
        var = ins.result.name
        if src.kind != "rows2d":
            raise TSCError(f"unpack expects streamed packed codes, got "
                           f"{src.kind} for %{ins.args[0]}")
        self.emit(f"# %{var} = unpack %{ins.args[0]} {{bits={bits}}}")
        self._emit_extract(src.expr, src.meta["nb"], bits, var)
        self.env[var] = _Val("reg", var, "u8")

    def op_gather(self, ins) -> None:
        table = self.env[ins.args[0]]
        if table.kind != "table":
            raise TSCError(f"gather table %{ins.args[0]} must be a resident "
                           f"input table")
        idx = self.materialize(ins.args[1])
        var = ins.result.name
        self.emit(f"# %{var} = gather %{ins.args[0]}, %{ins.args[1]}")
        self.emit(f"{var} = tl.load({table.expr} + {idx.expr})")
        self.env[var] = _Val("reg", var, ins.result.type.dtype)

    def op_decode(self, ins) -> None:
        table = self.env[ins.args[0]]
        codes = self.env[ins.args[1]]
        bits = dict(ins.attrs)["bits"]
        if table.kind != "table" or codes.kind != "rows2d":
            raise TSCError("decode expects a resident table and streamed codes")
        var = ins.result.name
        idx_var = self.tmp("idx")
        self.emit(f"# %{var} = decode %{ins.args[0]}, %{ins.args[1]} {{bits={bits}}}")
        self._emit_extract(codes.expr, codes.meta["nb"], bits, idx_var)
        self.emit(f"{var} = tl.load({table.expr} + {idx_var})")
        self.env[var] = _Val("reg", var, ins.result.type.dtype)

    def op_rot(self, ins) -> None:
        x = self.materialize(ins.args[0])
        m = self.materialize(ins.args[1])
        var = ins.result.name
        self.emit(f"# %{var} = rot %{ins.args[0]}, %{ins.args[1]}")
        self.emit(f"{var} = tl.dot({x.expr}, {m.expr}, allow_tf32=ALLOW_TF32)")
        self.env[var] = _Val("reg", var, ins.result.type.dtype)

    def op_cast(self, ins) -> None:
        x = self.materialize(ins.args[0])
        target = ins.args[1]
        var = ins.result.name
        self.emit(f"# %{var} = cast %{ins.args[0]}, {target}")
        self.emit(f"{var} = {x.expr}.to({_TL_DTYPE[target]})")
        self.env[var] = _Val("reg", var, target)

    def op_rescale(self, ins) -> None:
        x = self.materialize(ins.args[0])
        s = self.materialize(ins.args[1])
        var = ins.result.name
        self.emit(f"# %{var} = rescale %{ins.args[0]}, %{ins.args[1]}")
        self.emit(f"{var} = {x.expr} * {s.expr}[:, None]")
        self.env[var] = _Val("reg", var, ins.result.type.dtype)

    def op_store(self, ins) -> None:
        dst = ins.args[0]
        val = self.materialize(ins.args[1])
        attrs = dict(ins.attrs)
        note = f" {{cast={attrs['cast']}}}" if "cast" in attrs else ""
        self.emit(f"# store %{dst}, %{ins.args[1]}{note}")
        # The folded cast (or a defensive no-op when the value is already in
        # the output dtype) is the `.to(out.dtype)` of the handwritten store.
        expr = f"{val.expr}.to({dst}_ptr.dtype.element_ty)"
        self.emit(f"tl.store({dst}_ptr + rows[:, None].to(tl.int64) * D_OUT "
                  f"+ offs_d[None, :], {expr}, mask=rmask[:, None])")

    _DISPATCH = {"load": op_load, "unpack": op_unpack, "gather": op_gather,
                 "decode": op_decode, "rot": op_rot, "cast": op_cast,
                 "rescale": op_rescale, "store": op_store}

    def run(self) -> tuple[str, dict]:
        self.prologue_extras: dict[str, str] = {}
        for ins in self.module.instrs:
            handler = self._DISPATCH.get(ins.op)
            if handler is None:
                raise TSCError(f"Triton backend has no emission for op "
                               f"{ins.op!r}")
            handler(self, ins)
        return "\n".join(self.lines), self.prologue_extras


def generate_triton(module: Module, *, indexing_delta: int = 0) -> str:
    """Emit a standalone Python module with the fused kernel and a wrapper."""
    out = module.outputs[0]
    if len(module.outputs) != 1:
        raise TSCError("Triton backend supports exactly one output")
    head_dim = out.type.shape[-1]
    if not isinstance(head_dim, int):
        raise TSCError("Triton backend needs a concrete head dimension")
    # Streamed rank-2 input (the packed codes) defines NB for the wrapper.
    streamed2d = [v for v in module.inputs
                  if len(v.type.shape) == 2 and isinstance(v.type.shape[0], str)]
    if len(streamed2d) != 1:
        raise TSCError("Triton backend expects exactly one streamed rank-2 "
                       "input (the packed codes)")
    packed_in = streamed2d[0]
    nb = packed_in.type.shape[-1]
    inputs = [v.name for v in module.inputs]
    order = ", ".join(f"{n}_ptr" for n in inputs) + f", {out.name}_ptr"

    emitter = _Emitter(module, indexing_delta)
    body, extras = emitter.run()
    prologue = "\n".join(f"    {line}" for line in (
        "pid = tl.program_id(0)",
        "rows = pid * BLOCK_N + tl.arange(0, BLOCK_N)",
        "rmask = rows < N",
        f"offs_d = tl.arange(0, {head_dim})",
        "bh = rows // L",
        "pos = rows % L",
        "src_row = bh * MAXLEN + pos",
        *extras.values(),
    ))

    bits = [dict(i.attrs)["bits"] for i in module.instrs
            if i.op in ("unpack", "decode") and "bits" in dict(i.attrs)]
    meta = {"pipeline": module.name, "head_dim": head_dim, "nb": nb,
            "bits": bits[0] if bits else None,
            "indexing_delta": indexing_delta}

    return f'''# generated by turboquant_kv.tsc from IR; do not edit
import torch
import triton
import triton.language as tl

KERNEL_META = {meta!r}


@triton.jit
def {module.name}_kernel({order}, N, L, MAXLEN,
        BLOCK_N: tl.constexpr, ALLOW_TF32: tl.constexpr):
    D_OUT = {head_dim}
{prologue}
{body}


def run({", ".join(inputs)}, out=None, block_n=64, allow_tf32=False,
        num_warps=4, num_stages=2):
    """Wrapper mirroring kernel.tq_dequant: accepts a strided cache slice."""
    packed = {packed_in.name}  # the streamed rank-2 input drives the geometry
    lead = packed.shape[:-1]
    assert packed.shape[-1] == {nb}, "packed row bytes do not match the schedule"
    n = 1
    for s in lead:
        n *= s
    length = lead[-1]
    if packed.dim() >= 3 and packed.stride(-2) > 0:
        maxlen = packed.stride(-3) // packed.stride(-2)
    else:
        maxlen = length
    if out is None:
        out = torch.empty(*lead, {head_dim}, dtype={_TORCH_DTYPE[out.type.dtype]},
                          device=packed.device)
    grid = (triton.cdiv(n, block_n),)
    {module.name}_kernel[grid](
        {", ".join(inputs)}, out, n, length, maxlen,
        BLOCK_N=block_n, ALLOW_TF32=allow_tf32,
        num_warps=num_warps, num_stages=num_stages)
    return out
'''
