"""GPU execution evidence for the tensor-schedule compiler (tsc).

Runs on any host with a CUDA device, torch, and triton; nothing else is
required. Like bench_cuda_kernel.py, it REFUSES to fabricate what it cannot
measure: with no CUDA device it prints what is missing and exits 2.

What it does, per bit width (default 4 and 6), on the existing 24-shape
matrix (B in {1,4,16} x L in {1,8,64,128,512,2048,8192,16384}, H=4, D=128):

  1. compiles the canonical DSL schedule and execs the generated Triton
  2. numerical differential: generated kernel vs the pure PyTorch reference
     (an independent `centroids[idx] @ Pi * norms` formula), fp32 and tf32
  3. generated vs the handwritten kernel.tq_dequant on identical inputs
  4. timing: torch path, handwritten Triton, generated, and the
     generated-without-optimization arm (negative control), CUDA events
  5. a strided cache-slice correctness check (the (B,H,MAXLEN,NB) buffer
     sliced to :L, as TQPackedLayer hands out)
  6. compile-cache timing on this host (cold vs warm)

Gates: fp32 differential max abs error <= 1e-5; tf32 <= 3.125e-2 (the
retained A6000 bound); generated must equal the handwritten kernel
bit-for-bit under identical flags. Any gate failure exits 1.

Negative control: --inject-index-bug recompiles with an off-by-one in the
generated byte indexing. The differential MUST then fail; the script exits 0
only if the broken kernel was actually caught, and says so in the report.

Usage:
    python tools/run_gpu_differential.py                     # full run
    python tools/run_gpu_differential.py --bw 4              # one width
    python tools/run_gpu_differential.py --inject-index-bug  # control
    python tools/run_gpu_differential.py --fp32-timing       # slower, exact
    ... --out results/tsc_gpu_differential.json
"""
from __future__ import annotations

import argparse
import json
import os
import statistics
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "turboquant_kv"))

import torch                                        # noqa: E402

from packing import pack                            # noqa: E402
from tsc.compiler import compile_source             # noqa: E402
from tsc.examples import example_source             # noqa: E402
from tsc.runtime import load_generated              # noqa: E402

H, D = 4, 128
BATCHES = (1, 4, 16)
LENGTHS = (1, 8, 64, 128, 512, 2048, 8192, 16384)
FP32_GATE = 1e-5
TF32_GATE = 3.125e-2                                # retained A6000 TF32 bound


def timed(fn, inner=20, warmup=10, reps=3):
    for _ in range(warmup):
        fn()
    torch.cuda.synchronize()
    out = []
    s, e = torch.cuda.Event(True), torch.cuda.Event(True)
    for _ in range(reps):
        s.record()
        for _ in range(inner):
            fn()
        e.record()
        e.synchronize()
        out.append(s.elapsed_time(e) * 1e3 / inner)   # us per call
    return min(out), statistics.median(out)


def make_problem(bw: int, shape, seed: int = 0, device="cuda"):
    """Random codebook, random orthogonal rotation, random packed codes."""
    B, h, L = shape
    gen = torch.Generator().manual_seed(seed)
    idx = torch.randint(0, 2 ** bw, (B, h, L, D), generator=gen,
                        dtype=torch.uint8)
    centroids = torch.randn(2 ** bw, generator=gen).sort().values
    q, r = torch.linalg.qr(torch.randn(D, D, generator=gen))
    pi = (q * torch.sign(torch.diag(r))).contiguous()
    norms = torch.rand(B, h, L, generator=gen, dtype=torch.float16) + 0.5
    return {
        "packed": pack(idx, bw).to(device),
        "norms": norms.to(device),
        "centroids": centroids.to(device),
        "pi": pi.to(device),
    }, idx.to(device)


def reference(inputs, idx):
    """The dequantization written out independently of the compiler."""
    y = inputs["centroids"][idx.long()]
    x = y @ inputs["pi"]
    return (x * inputs["norms"].float().unsqueeze(-1)).to(torch.bfloat16)


def torch_path(inputs, bw):
    """The PyTorch dequantization as implemented in cache.py."""
    from packing import unpack
    idx = unpack(inputs["packed"].contiguous(), bw, D)
    flat = idx.reshape(-1, D)
    y = inputs["centroids"].index_select(
        0, flat.reshape(-1).to(torch.int32)).view(-1, D)
    x = y @ inputs["pi"]
    x = x * inputs["norms"].float().reshape(-1, 1)
    return x.to(torch.bfloat16).view(*idx.shape[:-1], D)


def run_width(bw: int, args, report: dict) -> bool:
    from kernel import tq_dequant as handwritten

    src = example_source(bw, D)
    delta = 1 if args.inject_index_bug else 0
    compiled = compile_source(src, indexing_delta=delta)
    compiled_noopt = compile_source(src, optimize_ir=False,
                                    indexing_delta=delta)
    gen = load_generated(compiled)
    gen_noopt = load_generated(compiled_noopt)

    width = {
        "bit_width": bw,
        "ir_instrs_optimized": compiled.stats.get("instrs_after"),
        "ir_instrs_unoptimized": compiled_noopt.stats.get("instrs_after"),
        "opt_stats": compiled.stats,
        "shapes": [],
        "strided": None,
    }
    report["widths"].append(width)
    ok = True

    for B in BATCHES:
        for L in LENGTHS:
            inputs, idx = make_problem(bw, (B, H, L))
            ref = reference(inputs, idx)
            row = {"batch": B, "cache_len": L, "rows": B * H * L}

            for label, tf32, gate in (("fp32", False, FP32_GATE),
                                      ("tf32", True, TF32_GATE)):
                got = gen.run(inputs["packed"], inputs["norms"],
                              inputs["centroids"], inputs["pi"],
                              allow_tf32=tf32)
                err = (got.float() - ref.float()).abs().max().item()
                hand = handwritten(inputs["packed"], inputs["norms"],
                                   inputs["centroids"], inputs["pi"], bw, D,
                                   allow_tf32=tf32)
                same = torch.equal(got, hand)
                got_noopt = gen_noopt.run(inputs["packed"], inputs["norms"],
                                          inputs["centroids"], inputs["pi"],
                                          allow_tf32=tf32)
                noopt_err = (got_noopt.float() - ref.float()).abs().max().item()
                row[f"max_abs_err_{label}"] = err
                row[f"noopt_max_abs_err_{label}"] = noopt_err
                row[f"matches_handwritten_{label}"] = same
                row[f"noopt_bitwise_equals_opt_{label}"] = torch.equal(
                    got_noopt, got)
                if args.inject_index_bug:
                    ok = ok and err > gate      # broken kernel must be caught
                else:
                    ok = ok and err <= gate and same and noopt_err <= gate

            if not args.inject_index_bug:
                tf32 = not args.fp32_timing
                fns = {
                    "torch_us": lambda: torch_path(inputs, bw),
                    "handwritten_us": lambda: handwritten(
                        inputs["packed"], inputs["norms"],
                        inputs["centroids"], inputs["pi"], bw, D,
                        allow_tf32=tf32),
                    "generated_us": lambda: gen.run(
                        inputs["packed"], inputs["norms"],
                        inputs["centroids"], inputs["pi"], allow_tf32=tf32),
                    "generated_noopt_us": lambda: gen_noopt.run(
                        inputs["packed"], inputs["norms"],
                        inputs["centroids"], inputs["pi"], allow_tf32=tf32),
                }
                row["timing_mode"] = "fp32" if args.fp32_timing else "tf32"
                for name, fn in fns.items():
                    row[name], _ = timed(fn, inner=args.inner,
                                         warmup=args.warmup, reps=args.reps)
            width["shapes"].append(row)
            print(f"bw={bw} B={B:>2} L={L:>5} "
                  f"err_fp32={row['max_abs_err_fp32']:.3e} "
                  f"err_tf32={row['max_abs_err_tf32']:.3e} "
                  + (f"gen={row.get('generated_us', 0):8.1f}us "
                     f"hand={row.get('handwritten_us', 0):8.1f}us "
                     f"torch={row.get('torch_us', 0):9.1f}us"
                     if "generated_us" in row else "(no timing: control run)"))

    # strided cache-slice correctness: a (B,H,MAXLEN,NB) buffer sliced to :L
    B, L, MAXLEN = 2, 1000, 16384
    gen_t = torch.Generator().manual_seed(7)
    idx = torch.randint(0, 2 ** bw, (B, H, MAXLEN, D), generator=gen_t,
                        dtype=torch.uint8)
    buf = pack(idx, bw).cuda()
    norms_buf = (torch.rand(B, H, MAXLEN, generator=gen_t,
                            dtype=torch.float16) + 0.5).cuda()
    base, _ = make_problem(bw, (1, 1, 1), seed=7)
    sliced = {"packed": buf[:, :, :L], "norms": norms_buf[:, :, :L],
              "centroids": base["centroids"], "pi": base["pi"]}
    got = gen.run(sliced["packed"], sliced["norms"], sliced["centroids"],
                  sliced["pi"], allow_tf32=False)
    ref = reference(sliced, idx.cuda()[:, :, :L])
    err = (got.float() - ref.float()).abs().max().item()
    width["strided"] = {"B": B, "L": L, "maxlen": MAXLEN,
                        "max_abs_err_fp32": err}
    if args.inject_index_bug:
        ok = ok and err > FP32_GATE
    else:
        ok = ok and err <= FP32_GATE
    return ok


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bw", type=int, nargs="*", default=[4, 6])
    ap.add_argument("--out", default=None)
    ap.add_argument("--inner", type=int, default=20)
    ap.add_argument("--warmup", type=int, default=10)
    ap.add_argument("--reps", type=int, default=3)
    ap.add_argument("--fp32-timing", action="store_true",
                    help="time the exact fp32 arms instead of tf32 (slower)")
    ap.add_argument("--inject-index-bug", action="store_true",
                    help="negative control: off-by-one in generated indexing;"
                         " the differential must FAIL for this run to pass")
    args = ap.parse_args()

    if not torch.cuda.is_available():
        print("This harness measures GPU execution and this host has no CUDA "
              "device.\nNothing was fabricated. Needed: an NVIDIA GPU, torch "
              "with CUDA, and triton.")
        raise SystemExit(2)
    try:
        import triton
    except Exception as err:
        print(f"triton is not importable here: {err!r}")
        raise SystemExit(2)

    started = time.time()
    report = {
        "device": torch.cuda.get_device_name(),
        "compute_capability": list(torch.cuda.get_device_capability()),
        "torch_version": torch.__version__,
        "triton_version": triton.__version__,
        "inject_index_bug": args.inject_index_bug,
        "gates": {"fp32": FP32_GATE, "tf32": TF32_GATE},
        "widths": [],
    }

    ok = True
    for bw in args.bw:
        ok = run_width(bw, args, report) and ok

    # compile cache behavior on this host
    import tempfile
    with tempfile.TemporaryDirectory() as cache_dir:
        src = example_source(args.bw[0], D)
        t0 = time.perf_counter()
        cold = compile_source(src, cache_dir=cache_dir)
        cold_s = time.perf_counter() - t0
        t0 = time.perf_counter()
        warm = compile_source(src, cache_dir=cache_dir)
        warm_s = time.perf_counter() - t0
        report["compile_cache"] = {
            "cold_ms": cold_s * 1e3, "warm_ms": warm_s * 1e3,
            "cold_hit": cold.cache_hit, "warm_hit": warm.cache_hit,
        }

    report["wall_s"] = time.time() - started
    report["passed"] = ok
    if args.inject_index_bug:
        report["control"] = ("PASS: injected off-by-one was caught by the "
                             "differential" if ok else
                             "FAIL: broken kernel was NOT caught")

    text = json.dumps(report, indent=2, sort_keys=True)
    if args.out:
        os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
        with open(args.out, "w") as fh:
            fh.write(text + "\n")
        print(f"wrote {args.out}")
    else:
        print(text)
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
